### PR TITLE
Bug 1239768 - Update Ukrainian localization

### PR DESCRIPTION
**Pull request by stenox**

### CODE REVIEW

**Comment by dylano** [comment]
Can you create a bugzilla bug for this and flag me for review?

**Comment by stenox** [comment]
Done, but not sure if it's filed correctly :) Please check and correct if needed.
Thanks!

**Comment by stenox** [comment]
@dylano Is this PR ok for merge? Just reminding...

**Comment by dylano** [comment]
Hi @stenox, I was trying to test this on Friday but I wasn't able to get it to load properly on device. I doubt that it's anything to do with this pull request but I need to do a little more work before I can merge.

**Comment by stenox** [comment]
Maybe I should close this PR and create new one with one commit?

**Comment by dylano** [comment]
Ok, I straightened out my issues. Looks good. Thanks @stenox!

**Pull request merged**
